CREATE TABLE Person(
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    year_of_birth int check(year_of_birth>1900)
);
CREATE TABLE Book(
    book_id int GENERATED By DEFAULT AS IDENTITY PRIMARY KEY,
    person int REFERENCES Person(person_id),
    time_of_assigning TIMESTAMP,
    name varchar(250) NOT NULL,
    author varchar(250),
    year_release int check(year_release>0)
);

INSERT INTO Person(name, year_of_birth) VALUES('Isabella, Anderson', 1995);
INSERT INTO Person(name, year_of_birth) VALUES('Levi, Wilson', 2005);
INSERT INTO Person(name, year_of_birth) VALUES('Noah, Williams', 1995);
INSERT INTO Person(name, year_of_birth) VALUES('Charlotte, Johnson', 1997);

INSERT INTO Book(name, author, year_release) VALUES('Don Quixote', 'Miguel de Cervantes', 1605);
INSERT INTO Book(name, author, year_release) VALUES('The Great Gatsby', 'Scott, Fitzgerald', 1925);
INSERT INTO Book(name, author, year_release) VALUES('Catch-22', 'Joseph, Heller', 1961);